### ISSUE TITLE
What is the input graph format?

### ISSUE THREAD

**Issue by ekg** [HanKruiger/tsnetwork#1]
It's not clear how to run the code. Would you please provide some examples?

**Comment by HanKruiger** [comment]
Thanks for your interest. This repository is here for 'historical purposes' only, and I don't plan on maintaining it. I've updated the description/readme accordingly.

The successor of this repository is at https://github.com/HanKruiger/tsNET. That should be a little bit less experimental. But it also doesn't have examples. I'll add an example to the readme on that repository.

**Comment by HanKruiger** [comment]
I will disable *Issues* on this repository in a few days, leaving some time for you to be able to read my response. 😉

**Comment by HanKruiger** [comment]
I've added an example to the readme.

The graphs I evaluated came in the [`.vna` format](https://gephi.org/users/supported-graph-formats/netdraw-vna-format/). But it should™️ support any format that [graph-tool](https://graph-tool.skewed.de/static/doc/quickstart.html#graph-i-o) supports.
